---
title: "- TITLE -"
author: "Oisin"
date: "2025-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library(tidyverse)
```

## Introduction

This analysis focuses on 
```{r universal adjustments, warning = FALSE, message = FALSE, results = 'hide'}
library(tidyverse)
load("../gradMS.Rdata")

# Data cleaning / pre-processing 
# gradMS[,1] # statistic
# gradMS[,2] # year
# gradMS[,3] # gender
# gradMS[,4] # field of study
# gradMS[,5] # NFQ Level
# gradMS[,6] # years since graduation
# gradMS[,7] # measure of statistic

# field of study and NFQ are irrelevant since they're always the same. We can remove them
# gradMS <- gradMS[,-c(4,5)]
# gradMS[,1] # statistic
# gradMS[,2] # year
# gradMS[,3] # gender
# gradMS[,4] # years since graduation
# gradMS[,5] # measure of statistic

gradMS %>%
  filter(Gender == "Other gender")
# there only exists one observations
# we can't make any meaningful analysis off of one point.
# We are hence deciding to omit this data

gradMS <- gradMS %>%
  filter(Gender != "Other gender") # this removes 300 rows

# we think it'd also make sense to pivot this table wider
# Increases readability and will make ggplots easier

gradMS_wider <- gradMS |> # we use a base pipe here because magrittr pipes play weird with '.'
  pivot_wider(names_from = Statistic, values_from = .)

# Some of these names are awkward, so we'll simplify them.
gradMS_wider <- gradMS_wider %>%
  rename(
    p25 = `P25 Earnings of Graduates`,
    p50 = `P50 Earnings of Graduates`,
    p75 = `P75 Earnings of Graduates`
  )
```

```{r question-specific adjustments}

```

## Including Plots


```{r myplot}

```

Here I should add an analysis of the plot.